### ISSUE TITLE
테이블 설계 학습 방법에 대해서 알려주세요!

### ISSUE THREAD

**Issue by youngsuk-kim** [team-dodn/devgem-topic#10]
재미니님! 몇번씩 영상 돌려보면서 개발에 관련된 지식을 정말 잘 배우고 있습니다! 감사합니다.

질문은 시중에 자료를 둘러보면 테이블 설계에 관련된 자료가 많이 없는데, 어떻게 하면 설계를 잘할 수 있을지에 대한 고민이 있습니다.
어떻게 하면 테이블 설계를 잘 할수있는지 학습 방법이나, 노하우에 대해서 알려주시면 정말 감사하겠습니다!

**Comment by youngsuk-kim** [comment]
테이블 설계 뿐만 아니라 일반적으로 개발 공부할 때 어떤식으로 학습하시는지 궁금합니다!

**Comment by geminiKim** [comment]
질문 감사합니다! 차후에 다뤄보도록 하겠습니다!👍
