### ISSUE TITLE
XXXService에 너무 많은 책임이 있다고 생각될 때가 있습니다.

### ISSUE THREAD

**Issue by K-jun98** [team-dodn/devgem-topic#11]
XXXService에 너무 많은 책임이 있다고 생각될 때가 있습니다.

작은 프로젝트에서도 하나의 서비스의 CRUD 메서드가 있고 많은 레포지토리에 의존하게 되는 경우가 있는데
객체 분리를 제대로 하지 않았다는 생각이 들 때가 있습니다. 하지만 아직 실무를 경험해 보지 못했고 많은 자료들을 보다 보면 XXXService라는 네이밍을
많이 사용하는 거 같은데 프로젝트 규모에 따라 Service를 분리하지 않는 것이 맞는지 네이밍은 어떻게 생각하시는지 궁금합니다.

**Comment by geminiKim** [comment]
질문 감사합니다! 차후에 다뤄보도록 하겠습니다!👍

**Comment by geminiKim** [comment]
to: https://www.youtube.com/watch?v=L3y3xk56SI8
